services:

  postgres:
    image: postgres:14.15
    env_file:
      - ../mepp-web/.env
    volumes:
      - ./.vols/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  nginx:
    image: nginx:stable
    env_file:
      - ../mepp-web/.env
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.vols/log/nginx:/var/log/nginx/
      - ../mepp-web/build:/usr/share/nginx/html
      - ./.vols/media:/usr/share/nginx/upload/media
      - ../mepp-web/.well-known:/usr/share/nginx/html/.well-known
      - static-content:/usr/share/nginx/html/static
    ports:
      - 8080:80
    restart: unless-stopped

  django:
    build: ../mepp-web
    image: mepp:2.x.x
    env_file:
      - ../mepp-web/.env
    volumes:
      - ./python/entrypoint.sh:/entrypoint.sh:ro
      - ./python/uwsgi.ini:/etc/uwsgi.ini:ro
      - static-content:/usr/src/app/static
      - ./.vols/log/django:/var/log/
      - ./.vols/media:/usr/src/app/media
    restart: unless-stopped

volumes:
  static-content:
